# Generated by Django 2.2.5 on 2019-11-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField(blank=True, help_text='Sensor number', null=True)),
                ('timestamp', models.DateTimeField(editable=False)),
                ('conveyor_belt', models.CharField(help_text='Conveyor Belt identification', max_length=10)),
                ('machine', models.CharField(help_text='Machine Name', max_length=80)),
                ('unit', models.CharField(help_text='Unit Name', max_length=80)),
                ('group', models.CharField(help_text='Group Name', max_length=80)),
                ('component', models.CharField(help_text='Component Name', max_length=80)),
                ('failure_mode', models.CharField(help_text='Failure Mode Name', max_length=80)),
                ('comments', models.CharField(help_text='Comments', max_length=300)),
                ('discipline', models.CharField(help_text='Discipline Name', max_length=80)),
                ('delay_min', models.IntegerField(blank=True, help_text='Delay Min', null=True)),
                ('avg_repair_time', models.IntegerField(blank=True, help_text='Average repair time (hours)', null=True)),
                ('avg_repair_cost', models.IntegerField(blank=True, help_text='Average repair cost (USD)', null=True)),
            ],
            options={
                'verbose_name': 'Failure',
                'verbose_name_plural': 'Failures',
            },
        ),
    ]
