# Generated by Django 2.2.7 on 2019-12-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerearth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation_bot_context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.CharField(help_text='conversation id', max_length=50, null=True)),
                ('value_type', models.CharField(help_text='value_type identification', max_length=50, null=True)),
                ('value', models.CharField(help_text='value identification', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Conversation_context',
                'verbose_name_plural': 'Conversation_contexts',
            },
        ),
    ]
